services:
  wiremock:
    image: wiremock/wiremock:3.10.0
    ports:
      - "8089:8080"
    volumes:
      - ../shared/test-fixtures/wiremock:/home/wiremock:ro
    command: --port 8080 --verbose --disable-banner
